title: [Miguel Fernández-Montes](miguelfmc.github.io/personalwebsite)
description: "UC Berkeley Master of Engineering | Data Scientist"
future: true
timezone: America/Los_Angeles
theme: jekyll-theme-slate
